### ISSUE TITLE
Kubernetes with external RDS does not work

### ISSUE THREAD

**Issue by msvechla** [blackducksoftware/hub#16]
Hello, 

we have been trying your kubernetes examples with an external RDS. Unfortunately it seems like the provided yml files no longer work with the current version of your applications.

Configuration parameters are first of all missing and when specified the postgres connections still result in `org.postgresql.util.PSQLException: FATAL: password authentication failed for user "blackduck"`.

Passwords have been set in the postgres instance, as well as in the yml files.

Things that are not working out of the box and have to be adjusted in the yml:

* postgres port not specified on container level:
```
- name: HUB_POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                key: HUB_POSTGRES_PORT
                name: hub-config
```

* hub-scan wont start because of missing vars in config map out of the box:
```
blackduck_hub_db_password: "pass"
    blackduck_hub_admin_db_password: "pass"
    blackduck_hub_bdio_db_password: "pass"
```

Still when adjusting the settings above connections to postgres do not work.
Have you actually tested these deployment files? 

Debugging is also not really possible, as I am unable to check which environment variables are actually expected by the application.

Can you verify that the kubernetes deployments with an external RDS actually work as described?

Best Regards

**Comment by msvechla** [comment]
I got it working now. Looks like the following varibles need to be set on every container:
```
- name: HUB_POSTGRES_REPORTER_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: HUB_POSTGRES_REPORTER_PASSWORD
                name: hub-config
          - name: HUB_POSTGRES_ADMIN_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: HUB_POSTGRES_ADMIN_PASSWORD
                name: hub-config
          - name: HUB_POSTGRES_USER_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: HUB_POSTGRES_USER_PASSWORD
                name: hub-config
```

It appears that the example Kubernetes yml files simply were outdated.
