### ISSUE TITLE
Kubernetes secrets & readonly

### ISSUE THREAD

**Issue by kstevenard** [blackducksoftware/hub#24]
On Kubernetes v1.10.3 I had to enable the feature gate ReadOnlyAPIDataVolumes=false to be able to have the webserver pod starting correctly when using custom certificates (setting those certs as explained in the README for Kubernetes). 
see: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#changelog-since-v193

> Changes secret, configMap, downwardAPI and projected volumes to mount read-only, instead of allowing applications to write data and then reverting it automatically. Until version 1.11, setting the feature gate ReadOnlyAPIDataVolumes=false will preserve the old behavior. (#58720, @joelsmith)

If not doing that then the webserver pods enters in a crashloop with the following
`
Root certificate: /opt/blackduck/hub/webserver/security/root.crt
Keeping IPv6 Listening.
Attempting to start filebeat version 5.5.2 (amd64), libbeat 5.5.2
Attempting to start webserver.
chown: /run/secrets/WEBSERVER_CUSTOM_KEY_FILE: Read-only file system
`

**Comment by robpacheco** [comment]
omg

**Comment by jayunit100** [comment]
omg :) great find ! we have a workaround, @robpacheco is leaving it in this thread.

**Comment by robpacheco** [comment]
Thanks for letting us know! I believe there are a few ways we can address this. My initial thoughts here are this is being caused by starting the nginx container as root. When this happens we switch users and modify some of the permissions just before doing so in order to run as a non-root user. Our containers also support the ability to start as a non-root user, we do this in the case of compose and swarm, but have not yet tried this with Kubernetes.

We'll give this a quick try and see if we can resolve this.

Thanks!

**Comment by jayunit100** [comment]
@robpacheco 's idea worked.  Heres a snippet you can use, obviously you can change the runAsUser to whatever you want, as long as its not root !
```
        securityContext:
          runAsUser: 1000
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: dir-webserver
        - name: nginx-certs
          secret:
            defaultMode: 420
            secretName: nginx-certs
```
